language: rust

os: linux

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
      env: RUSTFLAGS="-Zinstrument-coverage" LLVM_PROFILE_FILE="mshrtsr-%p-%m.profraw"

cache:
  directories:
    - ${HOME}/.cargo
    - ${HOME}/.rustup
before_cache:
  - rm -rf /home/travis/.cargo/registry

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_install: |
  if ! cargo install-update --version > /dev/null;
  then
  echo "Install cargo-update"
  cargo install cargo-update
  fi
  echo "Upgrade tools"
  cargo install-update -a
  if [ $TRAVIS_RUST_VERSION = "nightly" ];
  then
  echo "Install llvm-tools-preview"
  rustup component add llvm-tools-preview
  echo "Install or update grcov"
  cargo install-update -i grcov
  fi

before_script: |
  cargo fmt --version
  cargo fmt -- --check
  cargo clippy --version
  cargo clippy
  cargo clean

after_success: |
  if [ $TRAVIS_RUST_VERSION != "nightly" ];
  then
  grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info
  bash <(curl -s https://codecov.io/bash) -f lcov.info
  echo "Uploaded code coverage"
  fi
