jobs:
  build:
    docker:
      - image: circleci/rust

    steps:
      - checkout

      - run:
          name: rustup version
          command: rustup --version

      - run:
          name: cargo version
          command: cargo --version

      - run:
          name: install toolchains
          command: rustup component add clippy rustfmt

      - run:
          name: check format
          command: |
            cargo fmt --version
            cargo fmt -- --check

      - run:
          name: build
          command: cargo build

      - run:
          name: clippy
          command: |
            cargo clippy --version
            cargo clippy

      - run:
          name: test
          command: cargo test
