name: Build and Test

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - stable
          - beta
          - nightly
    name: ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v2

      - name: Switch toolchain version
        run: rustup default ${{ matrix.version }}

      - name: Rustup version
        run: rustup --version

      - name: Cargo version
        run: cargo --version

      - name: Clean
        run: cargo clean

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo test --verbose
