name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Rustup version
        run: rustup --version
      - name: Cargo version
        run: cargo --version
      - name: Install toolchains
        run: rustup component add clippy rustfmt
      - name: Check format
        run: |
          cargo fmt --version
          cargo fmt -- --check
      - name: Build
        run: cargo build --verbose
      - name: Lint
        run: |
          cargo clippy --version
          cargo clippy
      - name: Run tests
        run: cargo test --verbose
